### ISSUE TITLE
error 1023 in creating pool

### ISSUE THREAD

**Issue by clicx** [daos-stack/daos#582]
Hello,

I have managed to start a daos_server, while run client to create pool, always got failed:

orterun --allow-run-as-root -v -np 1 --host 192.168.80.11 --ompi-server file:/root/daos/daos_uri dmg create --size=1G --nvme=1G
failed to create pool: -1023

Logs here:
06/10-14:14:58.96 host-110 DAOS[15455] fi   INFO src/gurt/fault_inject.c:496 d_fault_inject_init() No config file, fault injection is OFF.
06/10-14:14:59.06 host-110 DAOS[15455] pmix ERR  src/cart/crt_pmix.c:575 crt_pmix_attach() PMIx_Lookup group daos_server failed, rc: -46, value.type 0.
06/10-14:14:59.06 host-110 DAOS[15455] pmix ERR  src/cart/crt_pmix.c:597 crt_pmix_attach() crt_pmix_attach group daos_server failed, rc: -1023.
06/10-14:14:59.06 host-110 DAOS[15455] grp  ERR  src/cart/crt_group.c:2488 crt_grp_attach() crt_pmix_attach GROUP daos_server failed, rc: -1023.
06/10-14:14:59.06 host-110 DAOS[15455] grp  ERR  src/cart/crt_group.c:2519 crt_grp_attach() crt_grp_attach, failed, rc: -1023.
06/10-14:14:59.06 host-110 DAOS[15455] grp  ERR  src/cart/crt_group.c:2388 crt_group_attach() crt_grp_attach to daos_server failed, rc: -1023.
06/10-14:14:59.06 host-110 DAOS[15455] grp  ERR  src/cart/crt_group.c:2451 crt_group_attach() crt_group_attach failed, rc: -1023.

**Comment by dinghwah** [comment]
Issue resolved on the new commit #6.

**Comment by dinghwah** [comment]
Resolved.

**Comment by clicx** [comment]
tested still the same result by playing with newest code in master branch
